/**
 * Regenerates `src/next/google-fonts.ts`, the export names of `next/font/google`.
 *
 * Next.js compiles `next/font/google` calls away at build time, so the module
 * has no runtime exports to copy. Its declarations are the only complete list
 * of font functions, and a named import only links when the name is listed.
 *
 * Usage: bun scripts/generate-google-fonts.ts [next version, default latest]
 */
const version = process.argv[2] ?? 'latest'
const response = await fetch(
  `https://unpkg.com/next@${version}/dist/compiled/@next/font/dist/google/index.d.ts`,
)
if (!response.ok) {
  throw new Error(`Could not download the font list: HTTP ${response.status}`)
}

const names = [
  ...(await response.text()).matchAll(/export declare function (\w+)/g),
].map(([, name]) => name)
if (names.length === 0) {
  throw new Error(`No font functions in ${response.url}`)
}

const resolved = response.url.match(/next@([^/]+)/)?.[1] ?? version
await Bun.write(
  `${import.meta.dirname}/../src/next/google-fonts.ts`,
  `// Generated by scripts/generate-google-fonts.ts from next@${resolved}. Do not edit.\nexport const GOOGLE_FONTS = [\n${names.map((name) => `  '${name}',`).join('\n')}\n]\n`,
)
console.info(`${names.length} fonts from next@${resolved}`)
